apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitness-app
  template:
    metadata:
      labels:
        app: fitness-app
    spec:
      containers:
      - name: fitness-app
        image: fitness-app:latest
        imagePullPolicy: IfNotPresent # Important for local Minikube images
        ports:
        - containerPort: 8000