apiVersion: v1
kind: Service
metadata:
  name: fitness-app-service
spec:
  type: NodePort # Exposes the service on each Node's IP at a static port
  selector:
    app: fitness-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000